version: '3.7'
services: 
  micro-asesorias-academicas:
   container_name: 'micro-asesorias-academicas' 
   image: anacarolinag/micro-asesorias:v1
   ports:
    - "6000:6000"
   networks: 
    - micro-asesorias-iud
