version: '3.7'
services: 
  micro-asesorias-academicas:
   container_name: 'micro-asesoriasiud1'
   image: anacarolinag/micro-asesorias:v4
   ports:
    - "5001:5000" 
   networks: 
    - microasesoriasiud

networks:
  microasesoriasiud:
    external: true